{{- range .Values.rbac }}
{{- $ns := .namespace }}
{{- range .subjects }}
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ .name | lower }}-{{ .role }}-{{ $ns }}
  namespace: {{ $ns }}
subjects:
  - kind: {{ .kind }}
    name: {{ .name }}
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: {{ .role }}
  apiGroup: rbac.authorization.k8s.io
---
{{- end }}
{{- end }}