kind: Secret
apiVersion: v1
metadata:
  name: gitlab-oauth-config
  namespace: {{ .Values.devspaces.cheCluster.namespace }}
  labels:
    app.kubernetes.io/component: oauth-scm-configuration
    app.kubernetes.io/part-of: che.eclipse.org
    argocd.argoproj.io/sync-wave: '0'
  annotations:
    che.eclipse.org/oauth-scm-server: gitlab
    che.eclipse.org/scm-server-endpoint: '{{ .Values.devspaces.gitlab.url }}'
data:
  id: {{ .Values.devspaces.gitlab.oauthClientId | b64enc }}
  secret: {{ .Values.devspaces.gitlab.oauthClientSecret | b64enc }}
type: Opaque