kind: ConfigMap
apiVersion: v1
metadata:
  name: {{ include "showroom.fullname" . }}-antora-config
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook": pre-upgrade
immutable: false
data:
  antora.yml: |-
    name: modules
    title: {{ .Values.antora.title }}
    version: master
    nav:
      - modules/ROOT/nav.adoc
    asciidoc:
      attributes:
        {{- range $key, $value := .Values.antora.asciidocAttributes }}
        {{ $key }}: {{ $value | quote }}
        {{- end }}
