apiVersion: tekton.dev/v1
kind: PipelineRun
metadata:
  generateName: {{ include "showroom.fullname" . }}-
  name: {{ include "showroom.fullname" . }}-pipelinerun
  annotations:
    # "helm.sh/hook": post-install
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec: 
  pipelineRef:
    name: {{ include "showroom.fullname" . }}
  params:
    - name: showroom-repo
      value: https://github.com/rh-opencodequest-origins/showroom.git
    - name: source-branch
      value: main 
  workspaces:
    - name: source
      volumeClaimTemplate:
        metadata:
          generateName: {{ include "showroom.fullname" . }}-pvc-
        spec:
          accessModes:
            - ReadWriteOnce
          resources:
            requests:
              storage: 2Gi
