apiVersion: v1
kind: Service
metadata:
  name: {{ include "showroom.fullname" . }}
  labels:
    {{- include "showroom.labels" . | nindent 4 }}
    
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    deployment: {{ .Release.Name }}
