nameOverride: "devspaces"
fullnameOverride: ""

namespace: "openshift-operators"

devspaces:
  subscription:
    channel: stable
    installPlanApproval: Automatic
    name: devspaces
    source: redhat-operators
    sourceNamespace: openshift-marketplace
  cheCluster:
    namespace: openshift-devspaces

argocd:
  enabled: true
  operatorgroup:
    syncwave: "-3"
  operator:
    syncwave: "-2"